[package]
name = "build-info-proc"
version = "0.0.13"
authors = ["Daniel Schemmel <daniel@schemmel.net>"]
edition = "2018"
publish = ["crates-io"]
repository = "https://github.com/danielschemmel/build-info/"
description = "Part of the build-info crate: This crate provides the proc-macros."
readme = "../README.md"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
anyhow = "1"
chrono = { version = "0.4", default_features = true }
format-buf = "1"
num-bigint = "0.2"
proc-macro2 = "1"
proc-macro-crate = "0.1"
proc-macro-hack = "0.5"
proc-macro-error = "1"
quote = "1"
serde_json = "1"
syn = "1"
thiserror = "1"

build-info-common = { version = "=0.0.13", path = "../build-info-common", features = ["enable-serde"] }

[features]
default = []
runtime = []
